cat <<EOF > ci.yml
name: Belajar-CI-Wildan

on: [push]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil code dari repo
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello Wildan! Robot DevOps tengah check code kau..."

      - name: Simulasi Error
        run: exit 1
EOF
